# Interactive component

## Top10 rating movie information in 2019 and 2020

<h3>Top10 Rating Movie in 2019, 2020 </h3>
<input type="radio" name="year" value="2019" checked="true">2019
<input type="radio" name="year" value="2020">2020

 <svg width="800" height="300"><rect x="0" y="0" width="800" height="300" fill="aliceblue"></rect><text id="xlabel" text-anchor="end" x="481.6666666666667" y="280">averageRating</text><g fill="none" font-size="10" font-family="sans-serif" text-anchor="middle" class="xAxis" transform="translate (215, 250)"><path class="domain" stroke="currentColor" d="M0,6V0H435V6"></path><g class="tick" opacity="1" transform="translate(21.749999999999922,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">7.6</text></g><g class="tick" opacity="1" transform="translate(65.24999999999996,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">7.8</text></g><g class="tick" opacity="1" transform="translate(108.75,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">8.0</text></g><g class="tick" opacity="1" transform="translate(152.24999999999986,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">8.2</text></g><g class="tick" opacity="1" transform="translate(195.75000000000009,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">8.4</text></g><g class="tick" opacity="1" transform="translate(239.24999999999991,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">8.6</text></g><g class="tick" opacity="1" transform="translate(282.75000000000017,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">8.8</text></g><g class="tick" opacity="1" transform="translate(326.25,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">9.0</text></g><g class="tick" opacity="1" transform="translate(369.74999999999983,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">9.2</text></g><g class="tick" opacity="1" transform="translate(413.25000000000006,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">9.4</text></g></g><g class="yAxis" transform="translate (215, 25)" fill="none" font-size="10" font-family="sans-serif" text-anchor="end"><path class="domain" stroke="currentColor" d="M-6,10H0V225H-6"></path><g class="tick" opacity="1" transform="translate(0,20.75)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Parasite</text></g><g class="tick" opacity="1" transform="translate(0,42.25)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Joker</text></g><g class="tick" opacity="1" transform="translate(0,63.75)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Avengers: Endgame</text></g><g class="tick" opacity="1" transform="translate(0,85.25)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Uri: The Surgical Strike</text></g><g class="tick" opacity="1" transform="translate(0,106.75)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">1917</text></g><g class="tick" opacity="1" transform="translate(0,128.25)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Klaus</text></g><g class="tick" opacity="1" transform="translate(0,149.75)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Ford v Ferrari</text></g><g class="tick" opacity="1" transform="translate(0,171.25)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Portrait of a Lady on Fire</text></g><g class="tick" opacity="1" transform="translate(0,192.75)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Knives Out</text></g><g class="tick" opacity="1" transform="translate(0,214.25)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">Jojo Rabbit</text></g></g><g id="plot" transform="translate (215, 25)"><line x1="0" y1="20" x2="435" y2="20" stroke="lightgrey"></line><line x1="0" y1="41.5" x2="435" y2="41.5" stroke="lightgrey"></line><line x1="0" y1="63" x2="435" y2="63" stroke="lightgrey"></line><line x1="0" y1="84.5" x2="435" y2="84.5" stroke="lightgrey"></line><line x1="0" y1="106" x2="435" y2="106" stroke="lightgrey"></line><line x1="0" y1="127.5" x2="435" y2="127.5" stroke="lightgrey"></line><line x1="0" y1="149" x2="435" y2="149" stroke="lightgrey"></line><line x1="0" y1="170.5" x2="435" y2="170.5" stroke="lightgrey"></line><line x1="0" y1="192" x2="435" y2="192" stroke="lightgrey"></line><line x1="0" y1="213.5" x2="435" y2="213.5" stroke="lightgrey"></line><circle cx="217.5" cy="20" r="3" fill="black"></circle><circle cx="195.75000000000009" cy="41.5" r="3" fill="black"></circle><circle cx="195.75000000000009" cy="63" r="3" fill="black"></circle><circle cx="195.75000000000009" cy="84.5" r="3" fill="black"></circle><circle cx="174.00000000000014" cy="106" r="3" fill="black"></circle><circle cx="152.24999999999986" cy="127.5" r="3" fill="black"></circle><circle cx="130.49999999999991" cy="149" r="3" fill="black"></circle><circle cx="130.49999999999991" cy="170.5" r="3" fill="black"></circle><circle cx="87.00000000000007" cy="192" r="3" fill="black"></circle><circle cx="87.00000000000007" cy="213.5" r="3" fill="black"></circle></g></svg><div style="padding: 10px;">

 <script type="text/javascript">
  
      //Width and height
      var w = 800;
      var h = 300;
      var margin = {top: 25, right: 150, bottom: 50, left: 215};
      var innerHeight = h - margin.top - margin.bottom;
      var innerWidth = w - margin.left - margin.right;

      var dataset2019 = [{
        "name": "Parasite",
        "runtimeMinutes": 132,
        "g1": "Comedy",
        "averageRating": 8.5,
        "numVotes": 730822,
        "boxoffice": "$258,632,621"
        },
        {
       "name": "Joker",
        "runtimeMinutes": 122,
        "g1": "Crime",
        "averageRating": 8.4,
        "numVotes": 1170784,
        "boxoffice": "$1,074,251,311"
        },
        {
        "name": "Avengers: Endgame",
        "runtimeMinutes": 181,
        "g1": "Action",
        "averageRating": 8.4,
        "numVotes": 1033089,
        "boxoffice": "$2,797,501,328"
        },
        {
        "name": "Uri: The Surgical Strike",
        "runtimeMinutes": 138,
        "g1": "Action",
        "averageRating": 8.4,
        "numVotes": 57785,
        "boxoffice": "$39,346,577"
        },
        {
        "name": "1917",
        "runtimeMinutes": 119,
        "g1": "Action",
        "averageRating": 8.3,
        "numVotes": 541457,
        "boxoffice": "$384,919,389"
        },
        {
        "name": "Klaus",
        "runtimeMinutes": 96,
        "g1": "Adventure",
        "averageRating": 8.2,
        "numVotes": 140162,
        "boxoffice": "NA"
        },
        {
        "name": "Ford v Ferrari",
        "runtimeMinutes": 152,
        "g1": "Biography",
        "averageRating": 8.1,
        "numVotes": 361169,
        "boxoffice": "$225,508,210"
        },
        {
        "name": "Portrait of a Lady on Fire",
        "runtimeMinutes": 122,
        "g1": "Drama",
        "averageRating": 8.1,
        "numVotes": 84712,
        "boxoffice": "$10,106,374"
        },
        {
        "name": "Knives Out",
        "runtimeMinutes": 130,
        "g1": "Comedy",
        "averageRating": 7.9,
        "numVotes": 582399,
        "boxoffice": "$311,605,581"
        },
        {
        "name": "Jojo Rabbit",
        "runtimeMinutes": 108,
        "g1": "Comedy",
        "averageRating": 7.9,
        "numVotes": 363411,
        "boxoffice": "$90,335,025"
        }
        ];
        
     var dataset2020 = [{
        "name": "Soorarai Pottru",
        "runtimeMinutes": 153,
        "g1": "Drama",
        "averageRating": 9.3,
        "numVotes": 109058,
        "boxoffice": "NA"
        },
        {
       "name": "Dara of Jasenovac",
        "runtimeMinutes": 130,
        "g1": "Drama",
        "averageRating": 8.8,
        "numVotes": 80545,
        "boxoffice": "$52,786"
        },
        {
        "name": "Hamilton",
        "runtimeMinutes": 160,
        "g1": "Biography",
        "averageRating": 8.4,
        "numVotes": 85090,
        "boxoffice": "NA"
        },
        {
        "name": "The Father",
        "runtimeMinutes": 97,
        "g1": "Drama",
        "averageRating": 8.3,
        "numVotes": 130262,
        "boxoffice": "$24,340,915"
        },
        {
        "name": "Demon Slayer the Movie: Mugen Train",
        "runtimeMinutes": 117,
        "g1": "Action",
        "averageRating": 8.3,
        "numVotes": 50833,
        "boxoffice": "$453,349,245"
        },
        {
        "name": "Soul",
        "runtimeMinutes": 100,
        "g1": "Adventure",
        "averageRating": 8.1,
        "numVotes": 304794,
        "boxoffice": "$120,957,731"
        },
        {
        "name": "Dil Bechara",
        "runtimeMinutes": 101,
        "g1": "Comedy",
        "averageRating": 8.1,
        "numVotes": 128032,
        "boxoffice": "$45,171"
        },
        {
        "name": "My Octopus Teacher",
        "runtimeMinutes": 85,
        "g1": "Documentary",
        "averageRating": 8.1,
        "numVotes": 50644,
        "boxoffice": "NA"
        },
        {
        "name": "The Trial of the Chicago 7",
        "runtimeMinutes": 129,
        "g1": "Drama",
        "averageRating": 7.8,
        "numVotes": 169367,
        "boxoffice": "$115,709"
        },
        {
        "name": "Another Round",
        "runtimeMinutes": 117,
        "g1": "Comedy",
        "averageRating": 7.7,
        "numVotes": 139127,
        "boxoffice": "$12,733,781"
        }
        ];
        
         
function update(data) {

       var yScale = d3.scaleBand()
      .domain(data.map(d => d.name))
      .range([10,innerHeight])
      
        
       var  yAxis = d3.axisLeft()
         .scale(yScale);
        
        svg.select(".yAxis")
           .transition()
           .duration(3000)
           .call(yAxis);
           
        d3.select("#plot")
        .selectAll("circle")
        .data(data)
        .transition()
        .duration(3000)
        .attr("cx", d => xScale(d.averageRating))
         
  }
         
 var action = "2019";
      d3.select("div")
      .selectAll("input")
      .on("click", function(event) { 
        action = d3.select(this).node().value;
        if (action == "2019") {
        datanew=dataset2019;
        update(datanew);
       
      } else {
        datanew=dataset2020;
        update(datanew);
        
      }
      });


      
   var cir = svg.selectAll("circle").data(dataset2019)
      cir.on("mouseover",function(event,d){
        var pt = d3.pointer(event)
        svg.append("text")
        .attr("id","tooltip")
        .attr("x",pt[0]+margin.left+7)
        .attr("y",pt[1]+margin.top+5)
        .text("voters: "+d.numVotes +"\n"+"Boxoffice:"+d.boxoffice)
        
      }
      ).on("mouseout",function(){
        svg.select("#tooltip").remove()

      })
      
    
 
    </script>
    
<div style="padding: 10px;"><a href="https://www.imdb.com/interfaces/">Data source: https://www.imdb.com/interfaces/</a></div>
 