--- 
title: "Movie Analysis"
author: "Haoyue Wang & Yanhao Ren"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The project theme we chose is the film industry. We choose this topic for two reasons, first of all, our group's two classmates all like watching movies, the second point is that the subject is the life, because almost everyone has seen the movie, so our analysis Angle can be more diversified, and the analysis results and image shows more and more people. 

We are interested in a lots of questions. Like After more than a hundred years of film history, do people in the past and today still enjoy watching the same genres of movies? With better techniques and scripts for making movies, do we have larger proportion of 5 stars movies? COVID-19 has affected people in so many ways, but in what ways has it affected the film industry?

To answer those questions, we further explore the relationship between various variables in the film industry, such as the relationship between the release year of different types of films and the total number of films, the relationship between the number of films and film scores, the relationship between film box office and film types, and the different performance of film box office in different years. At the same time, we also analyzed the impact of the epidemic on the film industry.
